# Setup
title:        Jonathan King
tagline:      Student Developer / Aspiring Computational Biologist
baseurl:      ""
paginate:     2

# About/contact
author:
  name:       Jonathan King
  url:        jonathanking@berkeley.edu

# github:
#   url:      http://jonathanking.github.io

# Gems
gems:
  - jekyll-paginate

#Others
# markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

  # syntax_highlighter: rouge