# Setup
title:        Jonathan King
tagline:      Student Programmer
baseurl:      ""
url:          http://jonathanking.github.io
paginate:     1

# About/contact
author:
  name:       Jonathan King
  url:        jonathanking@berkeley.edu

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge
input: GFM
  # syntax_highlighter: rouge